pipenv install flask
pipenv install flask-login
pipenv install flask-openid
pipenv install flask-mail
pipenv install flask-sqlalchemy
pipenv install sqlalchemy-migrate
pipenv install flask-whooshalchemy
pipenv install flask-wtf
pipenv install flask-babel
pipenv install guess_language
pipenv install flipflop
pipenv install coverage
